### ISSUE TITLE
Board Colors Inversion in Firefox iOS Night Mode

### ISSUE THREAD

**Issue by Khvalin** [lichess-org/chessground#223]
My Firefox iOS app has  a "Night mode" (not to be confused with "dark mode" -- https://support.mozilla.org/en-US/kb/night-mode-firefox-ios ) ON by default, which seems to invert webpage colors. It messes up piece and square colors making white appear as black and vice-versa.

![FIrefox_night_mode](https://user-images.githubusercontent.com/1132781/164169768-5bc921db-a358-4d71-ad17-d567b098913f.jpg)

**Comment by niklasf** [comment]
Thanks for reporting. Looks like Firefox issue https://github.com/mozilla-mobile/firefox-ios/issues/5951. Unfortunately websites can't do much about it, so closing here.
