### ISSUE TITLE
Disabling arrows and circles annotation

### ISSUE THREAD

**Issue by coffeeDev98** [lichess-org/chessground#232]
Hi, 
Is there any way to disable the annotations on the board....? Looking to implement my own annotation for the same

**Comment by ornicar** [comment]
https://github.com/lichess-org/chessground/blob/master/src/config.ts#L78

**Comment by coffeeDev98** [comment]
Hi @ornicar ,

Tried to disable it by doing the following

- ```drawable:false```
- ```drawable: {enabled: false,visible: false}```

Both don't seem to stop/disable the annotations....  Not sure if the way I'm disabling is right.

**Comment by ornicar** [comment]
That's the way to do it.

https://github.com/lichess-org/chessground-examples/blob/master/src/units/svg.ts#L94-L96

**Comment by coffeeDev98** [comment]
Thanks a lot ! @ornicar :)
