### ISSUE TITLE
Highlight square is not properly shown

### ISSUE THREAD

**Issue by fallncrlss** [lichess-org/chessground#237]
There's an issue with the fact that the highlighted/selected square is not aligned with the original one. But on lichens.org it's aligned fine.

Chessground v.8.3.5: <img width="601" alt="image" src="https://user-images.githubusercontent.com/54453888/192927301-c3664ef1-050d-4ea6-9d94-46294ebd4fdc.png">
Lichess: <img width="727" alt="image" src="https://user-images.githubusercontent.com/54453888/192927445-345f8a05-9598-4fc9-8c97-dede8172c816.png">

Of course, I've seen #201 issue, but there is no answer how to fix it

**Comment by niklasf** [comment]
Can you please share the (rendered) HTML/DOM and CSS of this page?

**Comment by fallncrlss** [comment]
@niklasf 
Deployed the sample with the issue: https://633700aebcb8df009c50cbe4--frabjous-tanuki-f16c66.netlify.app
![image](https://user-images.githubusercontent.com/54453888/193296390-d53d0e33-960b-43ed-a3bd-220626210ac0.png)

**Comment by niklasf** [comment]
There are two issues.

If you take the SVG background and divide it into 8 equal rows, you'll find that this won't match the square positions.

![image](https://user-images.githubusercontent.com/402777/193317382-80c08208-3b44-4a28-ae2f-4defd96aa276.png)

And then there's

```css
cg-board {
  border: 2px solid #ffe5b4;
}
```

messing with the layout.

**Comment by fallncrlss** [comment]
Thanks for the help!
