### ISSUE TITLE
Wrong piece movement issue

### ISSUE THREAD

**Issue by coffeeDev98** [lichess-org/chessground#241]
Hi @niklasf ,
I have been using chessground through another package [pgn-viewer](https://github.com/coffeeDev98/PgnViewerJS/tree/custom).
Not exactly sure as to what is causing this issue. It is pretty consistently occurring.  Any idea on why this could be occurring...?

Video of issue given below

https://user-images.githubusercontent.com/63295908/196850611-015fe8f1-72da-4855-9d9f-46b2b493d889.mov

**Comment by coffeeDev98** [comment]
https://user-images.githubusercontent.com/63295908/196850554-be0fa83d-9e6c-434f-8ca7-72421e1bd465.mov

**Comment by ornicar** [comment]
That would be due to the page layout shifting after chessground is initialized, and chessground didn't update the board coordinates.

What application is that, where can we see it?

**Comment by Siderite** [comment]
> That would be due to the page layout shifting after chessground is initialized, and chessground didn't update the board coordinates.

This also causes issues in other places when _something_ changes the layout. I've solved it by periodically checking the position of the board and triggering a body resize event when it changes, but I think this kind of functionality should be embedded in Chessground.

 I don't understand why Chessground has to cache the board coordinates in the first place and not use the current ones.
