### ISSUE TITLE
Clicking one of your own pieces should always select that piece - never deselect it

### ISSUE THREAD

**Issue by SymboLinker** [lichess-org/chessground#242]
When touching one of your own pieces, it gets selected.
When touching the same piece again, it gets deselected.

From a practical point of view, it seems more logical to keep the piece selected - especially when playing on a touch screen with time pressure. While playing [Puzzle Storm](https://lichess.org/storm):
- I mostly play with both thumbs, touching the original square with one and the destination square with the other.
- I sometimes select the piece I expect to do a move with and then think through a bit more. When I conclude that I've found the solution, I sometimes touch both the original square (again) and the destination square, without effect.
- The result is a timeloss that is my own mistake, but still it feels like the deselecting-behaviour is weird and unnecessary.

**Comment by niklasf** [comment]
No doubt many users rely on exactly this behavior. I find it quite intuitive, and it's consistent with how selections work in pretty much any environment.
