### ISSUE TITLE
Puzzles but for math problems.

### ISSUE THREAD

**Issue by nevesanjos** [lichess-org/chessground#244]
Is it possible to adapt the puzzles feature for math problems? I was thinking that it would be great having such an app that updates your rating on math.

**Comment by niklasf** [comment]
This repository is the chessboard component, which will not be very useful for your project. But you could definitely interpret math problems as opponents in [Glicko2-rated games](https://en.wikipedia.org/wiki/Glicko_rating_system), just like Lichess does with puzzles.
