### ISSUE TITLE
Error on analysis board

### ISSUE THREAD

**Issue by shubik22** [lichess-org/chessground#254]
Hi folks, when going through an interactive study ([this one](https://lichess.org/study/XrQZOclp)), I'm running into an issue where I can't make any moves.  I'm seeing this error in the devtools console:

<img width="1440" alt="Screen Shot 2023-04-02 at 8 44 29 AM" src="https://user-images.githubusercontent.com/5737046/229353717-aca6bf83-ad73-44de-817e-ba340c7bf430.png">

Looks like the exception might be getting thrown in the [key2pos function](https://github.com/lichess-org/chessground/blob/5749b54163a1508699036f04d7248f1e63f44dcd/src/util.ts#L9).

My browser: Chrome Version 111.0.5563.146 (Official Build) (x86_64)

Let me know if you need any other info from me, thanks!

**Comment by ornicar** [comment]
https://github.com/lichess-org/lila/pull/12618
