### ISSUE TITLE
Detect any click on the board 

### ISSUE THREAD

**Issue by gabrilator** [lichess-org/chessground#257]
Hey! Thanks for the amazing work.
Is there a way to detect any click on the board? this would be super helpful for animations, for example, that would reset when the user clicks on the board.

Cheers!

**Comment by chao-mu** [comment]
Yes. the select event. However there is a bug where it fires twice if you click an unoccupied square on mobile.

**Comment by Anupya** [comment]
Seems like this issue can be closed?
