### ISSUE TITLE
Pgn file download is missing extension

### ISSUE THREAD

**Issue by shtayerc** [lichess-org/chessground#265]
Hello,

I noticed that PGN file downloaded bellow analysis board is named just "download" without any extension. I suppose it should be named download.pgn or something like that. The file contains valid PGN, but Chessbase does not recognise it and refuses to open it.

Steps to reproduce:
- Open game in analysis mode - for example https://lichess.org/Sxov6E94
- click Share & export
- click any link in PGN row (Download annotated, Download raw, Download imported)
- file named "download" is downloaded

**Comment by niklasf** [comment]
Thanks for reporting. https://github.com/lichess-org/lila/commit/57ad273a3cc7b0a3b05aad0460be37d7fa49ce26 will fix it with the next update.
