### ISSUE TITLE
How to implement piece drag and drop feature like https://lichess.org/editor?

### ISSUE THREAD

**Issue by invisionweb** [lichess-org/chessground#281]
I'm finding it difficult to create a piece drag and drop feature like https://lichess.org/editor. The extra new pieces will be outside the board. How the event **afterNewPiece()** can be triggered?

```
movable?: {
    events?: {
      after?: (orig: cg.Key, dest: cg.Key, metadata: cg.MoveMetadata) => void; // called after the move has been played
      afterNewPiece?: (role: cg.Role, key: cg.Key, metadata: cg.MoveMetadata) => void; // called after a new piece is dropped on the board
    };
  };
```

**Comment by uribalb** [comment]
> I'm finding it difficult to create a piece drag and drop feature like https://lichess.org/editor. The extra new pieces will be outside the board. How the event **afterNewPiece()** can be triggered?
> 
> ```
> movable?: {
>     events?: {
>       after?: (orig: cg.Key, dest: cg.Key, metadata: cg.MoveMetadata) => void; // called after the move has been played
>       afterNewPiece?: (role: cg.Role, key: cg.Key, metadata: cg.MoveMetadata) => void; // called after a new piece is dropped on the board
>     };
>   };
> ```

Look into the Lichess' source code

**Comment by ornicar** [comment]
Please, this is not an issue.
