### ISSUE TITLE
Valid move snapping for draw arrow not working correctly

### ISSUE THREAD

**Issue by KartikWatts** [lichess-org/chessground#307]
#### Description:

During my recent game analysis, I encountered a minor issue with the valid move-snapping functionality for the draw arrow.

#### Problem:

Even when `defaultSnapToValidMove` is true, if the right mouse button is pressed and the pointer moves outside of the chessboard before being released, the snapping feature fails to work as expected. This occurs because the `cur.snapToValidMove `value is not being updated properly.

#### Steps to Reproduce:

1. Press and hold the right mouse button to draw an arrow.
2. Move the pointer outside of the chessboard.
3. Bring the pointer back onto the chessboard.

Attaching GIF for reference:

![chessground_snap](https://github.com/user-attachments/assets/6aaa1a9e-a88c-420d-8809-00ae59a36f6b)

#### Expected Behavior:
The draw arrow should snap to the valid move after the pointer returns to the chessboard.

#### Actual Behavior:
The draw arrow does not snap to the valid move because `cur.snapToValidMove` is not updated.

**Comment by KartikWatts** [comment]
Considering it as a bug, a small fix was required, raised a PR to close this: https://github.com/lichess-org/chessground/pull/308. Regards.

**Comment by fitztrev** [comment]
Hi, this is actually intended

https://github.com/lichess-org/lila/issues/11713
https://github.com/lichess-org/lila/issues/9095
https://github.com/lichess-org/lila/issues/8313
https://github.com/lichess-org/lila/issues/15073

**Comment by KartikWatts** [comment]
Oops got it 🙈. Thanks.
